/* ── Session Recap & Notes ─────────────────────────────────────
 * A sidebar panel for the DM to quickly jot session notes,
 * then generate a formatted recap for the players.
 * Data is stored in localStorage + synced to Firebase via campaignStore.
 * ─────────────────────────────────────────────────────────────── */

import { useState, useEffect } from "react";
import { useCampaignStore } from "@/stores/campaignStore";
import { useUiStore } from "@/stores/uiStore";
import { Button } from "@/components/ui/Button";

interface SessionBullet {
  id: string;
  text: string;
  timestamp: number;
}

const STORAGE_KEY = "vtt-session-recap-bullets";

function uid(): string {
  return `sr_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function loadBullets(): SessionBullet[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

function saveBullets(bullets: SessionBullet[]) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(bullets));
}

export function SessionRecapNotes() {
  const campaign = useCampaignStore((s) => s.campaign);
  const showToast = useUiStore((s) => s.showToast);

  const [bullets, setBullets] = useState<SessionBullet[]>(loadBullets);
  const [newBullet, setNewBullet] = useState("");
  const [recapText, setRecapText] = useState("");

  // Auto-save bullets
  useEffect(() => {
    saveBullets(bullets);
  }, [bullets]);

  const addBullet = () => {
    const text = newBullet.trim();
    if (!text) return;
    const bullet: SessionBullet = {
      id: uid(),
      text,
      timestamp: Date.now(),
    };
    setBullets((prev) => [...prev, bullet]);
    setNewBullet("");
  };

  const removeBullet = (id: string) => {
    setBullets((prev) => prev.filter((b) => b.id !== id));
  };

  const clearBullets = () => {
    setBullets([]);
    setRecapText("");
    localStorage.removeItem(STORAGE_KEY);
    showToast({ message: "Session notes cleared.", type: "info" });
  };

  const generateRecap = () => {
    if (bullets.length === 0) {
      showToast({ message: "Add some session notes first.", type: "warning" });
      return;
    }

    const campaignName = campaign?.name ?? "the campaign";
    const date = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const sorted = [...bullets].sort((a, b) => a.timestamp - b.timestamp);
    const bulletList = sorted
      .map((b) => `• ${b.text}`)
      .join("\n");

    const recap = [
      `# Session Recap — ${campaignName}\n`,
      `**Date:** ${date}\n`,
      "## What Happened\n",
      bulletList,
      "\n",
      "---\n",
      "*Recap generated by STᚱ VTT*",
    ].join("\n");

    setRecapText(recap);
    showToast({ message: "Recap generated! Copy it to share with players.", type: "success" });
  };

  const copyRecap = async () => {
    if (!recapText) return;
    try {
      await navigator.clipboard.writeText(recapText);
      showToast({ message: "Recap copied to clipboard!", type: "success" });
    } catch {
      showToast({ message: "Failed to copy. Select and copy manually.", type: "error" });
    }
  };

  return (
    <div className="rounded-xl border border-surface-700 bg-surface-850 p-5 space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-semibold uppercase tracking-wider text-surface-400">
          📝 Session Recap Notes
        </h3>
        {bullets.length > 0 && (
          <button onClick={clearBullets} className="text-[11px] text-surface-500 hover:text-warrior-400 transition-colors">
            Clear All
          </button>
        )}
      </div>

      {/* Bullet Input */}
      <div className="flex gap-2">
        <input
          type="text"
          value={newBullet}
          onChange={(e) => setNewBullet(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && addBullet()}
          placeholder="What happened this session..."
          className="flex-1 rounded-lg border border-surface-700 bg-surface-800 px-3 py-2 text-sm text-surface-100 placeholder:text-surface-500 focus:border-accent-500 focus:outline-none"
        />
        <Button size="sm" onClick={addBullet} disabled={!newBullet.trim()}>
          + Add
        </Button>
      </div>

      {/* Bullet List */}
      {bullets.length > 0 && (
        <div className="space-y-1.5 max-h-48 overflow-y-auto">
          {[...bullets]
            .sort((a, b) => b.timestamp - a.timestamp)
            .map((b) => (
              <div
                key={b.id}
                className="group flex items-start gap-2 rounded-lg bg-surface-800 px-3 py-2"
              >
                <span className="text-surface-500 mt-0.5 shrink-0">•</span>
                <p className="flex-1 text-sm text-surface-200">{b.text}</p>
                <button
                  onClick={() => removeBullet(b.id)}
                  className="shrink-0 text-surface-500 hover:text-warrior-400 opacity-0 group-hover:opacity-100 transition-all text-xs"
                >
                  ✕
                </button>
              </div>
            ))}
        </div>
      )}

      {/* Generate Recap Button */}
      <div className="flex gap-2">
        <Button
          variant="secondary"
          size="sm"
          onClick={generateRecap}
          disabled={bullets.length === 0}
          className="flex-1"
        >
          ✨ Generate Recap
        </Button>
      </div>

      {/* Recap Output */}
      {recapText && (
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-surface-400">Recap Preview</span>
            <button
              onClick={copyRecap}
              className="text-[11px] text-accent-400 hover:text-accent-300 transition-colors"
            >
              📋 Copy to Clipboard
            </button>
          </div>
          <pre className="rounded-lg border border-surface-700 bg-surface-800 p-4 text-xs text-surface-200 leading-relaxed whitespace-pre-wrap font-sans max-h-60 overflow-y-auto">
            {recapText}
          </pre>
        </div>
      )}
    </div>
  );
}
